# This is a basic workflow to help you get started with Actions

name: Greeting form Linqi

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps: 
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Joey
        MIDDLE_NAME: Linqi
        LAST_NAME: LIU
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      
